### ISSUE TITLE
Unit test for nil

### ISSUE THREAD

**Issue by DylanMeeus** [DylanMeeus/hasgo#51]
Some functions' unit tests don't test for nil as receiver / input. Need to go over the unit tests and make sure they all test for this and return the expected result. (Similar for the empty slice which seems to be present more often)

**Comment by GoFightNguyen** [comment]
Where are the functions' unit tests located?

**Comment by DylanMeeus** [comment]
You can find them in the 'types' directory, where it runs them for ints, bools, strings and a custom type 👍

**Comment by GoFightNguyen** [comment]
In both `Test_StringsMapOriginalUnchanged` and `Test_StringsSort`, both tests fail when adding scenarios for `nil` and `Strings{}`. This is because both tests utilize `EqualsOrdered`, and fail when that is true.
Since both scenarios result in `Strings{}`, then `EqualsOrdered` is true.

@DylanMeeus How do you think this should be handled?

**Comment by DylanMeeus** [comment]
Thanks for looking into this @GoFightNguyen ! 

I'd say that the functions `Test_StringsMapOriginalUnchanged` and `Test_StringSort` should become smarter and deal with empty/nil input as an edge case. So check that the original != output, only when the input is not nil or empty. 

What do you think?

**Comment by GoFightNguyen** [comment]
Thanks, I'll proceed like that. I had the same thoughts, but wanted to ensure I wasn't missing something or breaking an explicit paradigm

**Comment by DylanMeeus** [comment]
Great, thanks!
